### PR TITLE
Update dorita980

### PR DESCRIPTION
**Pull request by TheRealArthurDent**
Since koalazak seems to have discontinued support for dorita980, why not go for the updated @karlvr/dorita980 that actually supports node 18?

### CODE REVIEW

**Review by fritz47110815 — APPROVED** [review]
good idea

**Comment by ErykxK** [comment]
hello. I have a problem with the roomba adapter. I have Docker and iobroker installed on the "loxberry". Before the loxberry 3.0.0.5 update, the roomba adapter worked without any problem. Despite entering the correct data into the adapter (IP, username, password) it does not work even though it lights up green....
Zrzut ekranu 2023-04-29 o 09 57 18

**Comment by TheRealArthurDent** [comment]
@ErykxK pretty sure this has nothing to do with loxberry and its version.

Looking at your last screenshot, iobroker is running with node 18 which causes the issue described in https://github.com/iobroker-community-adapters/ioBroker.roomba/issues/143.
I assume you're using iobroker in docker and have recently upgraded to version 8.#.# (or more likely are just using iobroker:latest and docker has recently implicitly updated to an 8.#.# version of that image).

Pinning the docker image to version 7.2.0, which uses node 16, will work around this issue until this PR is merged or the adapter has been fixed in any other way to work with node 18.

In case my above assumption is correct, you might wanna inform about docker versioning and reconsider using "latest" in any sort of productive environment.

**Comment by ErykxK** [comment]
yep. you were right! after reinstalling iobroker (this time version 7.2.0) everything works fine

**Comment by fritz47110815** [comment]
The problems came back with 18.6 even with @karlvr/dorita980 - or do I have problems with my installation?

**Comment by fritz47110815** [comment]
@TheRealArthurDent It seems 14.x has problems. Maybe it should be removed out of the code, because it's desupported already.

**Review by fritz47110815 — APPROVED** [review]

**Comment by fritz47110815** [comment]
I think it's fine now. What is the next step?

**Comment by TheRealArthurDent** [comment]
> What is the next step?

Well. Someone with write access to the repo (https://github.com/orgs/iobroker-community-adapters/people) has to merge this PR and create a new release.
@Apollon77 You appear to be the guy in charge of this repo (at least the most active contributer. May I ask you to do that? :)

**Comment by mcm1957** [comment]
@fritz47110815 
@TheRealArthurDent 

Thanks for your effort. I can merge the PR and create a new release. 
But before doing this I would like to ensure the someone is ther to TEST the new release and to FIX issues eventually occuring. I do not have the hardware (= roomba) to test anything. (My Rooba is an old stipid model which has difficulties to find its base but has no connection to anything else than the power supply).

So please let me know if there's someone out to take the responsibility for the changes and is willing to do his/her best to fix eventually problems.

McM1957
@Apollon77 FYI and eventually veto if you know more facts.

**Comment by Apollon77** [comment]
Go ahead, I would also onlymerge and release a version

**Comment by mcm1957** [comment]
Ok, I'll do the netx few days

**Comment by TheRealArthurDent** [comment]
Hey @mcm1957,

sorry for the late response. :(
I was a bit hestitant to speak-up as a tester, since I only have a 960 which means that I can just test basic connectivity but not much else. So I wanted to wait if anybody else raises their hands. Of course I then forgot to respond a bit later. -.-

Anyway, thank you very much for releasing this. I'll test it asap (pry this afternoon/evening) and leave a comment on https://github.com/iobroker-community-adapters/ioBroker.roomba/issues/143.

**Comment by mcm1957** [comment]
@TheRealArthurDent 
No problem. I confirmed with Apollon77 to build a new release.
I will release a newer 1.2.1 today or tomorrow. Thkis release will not have any fixes but contain some more updates on dependencies. I wanted to seperate those updates from your PR to easeeventually searching for problems.

As I already states I do not have any (useable) Roomba for tests. So I can only check that a release is nbuildable and can be installed. As you have at least one unit which can communicate with the adapter I'm glad if you do some tests.

**Pull request merged**
